//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNewBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string author { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string language { get; set; }
        public string imageUrl { get; set; }
    }
}
