//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNewBlog.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int id { get; set; }
        [StringLength(50, MinimumLength = 4)]
        public string userName { get; set; }
        [StringLength(50, MinimumLength = 4)]
        public string userPassword { get; set; }
        public Nullable<int> imageHeader { get; set; }
        [UserValidation]
        [StringLength(50, MinimumLength = 4)]
        public string userAccount { get; set; }
        public int isAdmin { get; set; }
        public bool RememberMe { get; set; }
    }
}
